import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

function BadStopwatch() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    console.log("Bad stopwatch useEffect");

    setInterval(() => {
      setCount((count) => count + 1);
    }, 100);
  }, []);

  return <div>{count.toFixed(1)}</div>;
}

function GoodStopwatch() {
  const [count, setCount] = useState(0);

  useEffect(() => {
    console.log("Good stopwatch useEffect");
    const interval = setInterval(() => {
      setCount((count) => count + 1);
    }, 100);

    return () => clearInterval(interval);
  }, []);

  return <div>{count.toFixed(1)}</div>;
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
          <BadStopwatch />
          <GoodStopwatch />
        </div>
      </main>
    </>
  );
}
